In [1]:
import pandas as pd

In [2]:
df = pd.read_pickle('../BoardGameGeek/data_prepped/pivot_by_game.pk1')
df.fillna(0, inplace=True)
sdf = df.astype(pd.SparseDtype(int, fill_value=0))
del df
sdf

uID,1,2,3,4,5,6,7,8,9,10,...,217194,217195,217196,217205,217206,217208,217209,217210,217212,217215
ID,,,,,,,,,,,,,,,,,,,,,
1,7,7,7,10,0,7,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,5,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,8,7,10,8,7,10,9,0,8,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,6,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,8,0,7,10,10,6,0,0,4,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3050,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3051,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3052,0,0,0,0,0,2,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3053,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3054,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
# Concatenate in one segment at a time in case of memory/address overflow
df2 = pd.read_pickle('../BoardGameGeek/data_prepped/pivot_by_game2.pk1')
df2.fillna(0, inplace=True)
sdf2 = df2.astype(pd.SparseDtype(int, fill_value=0))
del df2
sdf = pd.concat([sdf, sdf2], axis=0)
sdf

uID,1,2,3,4,5,6,7,8,9,10,...,217209,217210,217212,217214,217215,217217,217218,217219,217220,217221
ID,,,,,,,,,,,,,,,,,,,,,
1,7,7,7,10,0,7,0,0,1,0,...,0,0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
2,0,0,5,0,0,0,0,0,0,0,...,0,0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3,8,7,10,8,7,10,9,0,8,0,...,0,0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
4,0,0,0,0,0,6,0,0,0,0,...,0,0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5,8,0,7,10,10,6,0,0,4,0,...,0,0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6982,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0.0,0,0.0,0.0,0.0,0.0,0.0
6983,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0.0,0,0.0,0.0,0.0,0.0,0.0
6988,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0.0,0,0.0,0.0,0.0,0.0,0.0
6990,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0.0,0,0.0,0.0,0.0,0.0,0.0
6993,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0.0,0,0.0,0.0,0.0,0.0,0.0

In [4]:
# Save a snapshot of the pivot by game

sdf.to_pickle('../BoardGameGeek/data_prepped/pivot_by_game_conc.pk1')

In [5]:
# Concatenate in one segment at a time in case of memory/address overflow
df2 = pd.read_pickle('../BoardGameGeek/data_prepped/pivot_by_game3.pk1')
df2.fillna(0, inplace=True)
sdf2 = df2.astype(pd.SparseDtype(int, fill_value=0))
del df2
sdf = pd.concat([sdf, sdf2], axis=0)
sdf

uID,1,2,3,4,5,6,7,8,9,10,...,217212,217214,217215,217217,217218,217219,217220,217221,217222,217223
ID,,,,,,,,,,,,,,,,,,,,,
1,7,7,7,10,0,7,0,0,1,0.0,...,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0,0,5,0,0,0,0,0,0,0.0,...,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,8,7,10,8,7,10,9,0,8,0.0,...,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,0,0,0,0,6,0,0,0,0.0,...,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,8,0,7,10,10,6,0,0,4,0.0,...,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16088,0,0,0,0,0,0,0,0,0,NaN,...,0,0.0,0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
16105,0,0,0,0,0,0,0,0,0,NaN,...,0,0.0,0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
16110,0,0,0,0,0,0,0,0,0,NaN,...,0,0.0,0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
16112,0,0,0,0,0,0,0,0,0,NaN,...,0,0.0,0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
16130,0,0,0,0,0,0,0,0,0,NaN,...,0,0.0,0,0.0,0.0,0.0,0.0,NaN,0.0,0.0

In [6]:
# Post-process and save a snapshot of the pivot by game
del sdf2
sdf.fillna(0, inplace=True)
sdf = sdf.astype(pd.SparseDtype(int, fill_value=0))
sdf.to_pickle('../BoardGameGeek/data_prepped/pivot_by_game_conc2.pk1')

In [7]:
from sklearn.neighbors import NearestNeighbors
knn = NearestNeighbors(metric='cosine', algorithm='brute')
knn.fit(sdf.values)
distances, indices = knn.kneighbors(sdf.values, n_neighbors=5)

In [8]:
from joblib import dump

dump(knn, 'bgg_knn_5.joblib')

['bgg_knn_5.joblib']

In [76]:
arr = sdf.iloc["16088"].to_numpy()

distances, indices = knn.kneighbors(arr)
indices

TypeError: Cannot index by location index with a non-integer key

In [24]:
indices

array([[   0, 2677, 4690,  406,  470],
       [   1,   29,  867, 1443,  689],
       [   2,  430,   11,   39,   84],
       ...,
       [6055, 5903, 5896, 5383, 1563],
       [6056, 6004, 3148, 5346, 5873],
       [6057, 4042, 5516, 4553, 3005]], dtype=int64)

In [29]:
df = pd.read_csv("../Resources/bgg-19m-reviews.csv", index_col = 0)
df

,user,rating,comment,ID,name
0,Torsten,10.0,NaN,30549,Pandemic
1,mitnachtKAUBO-I,10.0,Hands down my favorite new game of BGG CON 200...,30549,Pandemic
2,avlawn,10.0,I tend to either love or easily tire of co-op ...,30549,Pandemic
3,Mike Mayer,10.0,NaN,30549,Pandemic
4,Mease19,10.0,This is an amazing co-op game. I play mostly ...,30549,Pandemic
...,...,...,...,...,...
18964802,Ceryon,3.1,NaN,1752,Haps
18964803,Gregarius,2.0,"I hated this game. Too complicated to set up, ...",1752,Haps
18964804,Lajos,2.0,Sold in Geekauction for 3 GG.,1752,Haps
18964805,Imagine,1.0,This game is not for me - I just didn&#039;t g...,1752,Haps
18964806,gonzo104,1.0,NaN,1752,Haps

In [30]:
df = df.drop(['comment', 'rating', 'user'], axis=1)
df.drop_duplicates(inplace=True, ignore_index=True)
df

           ID                                               name
0       30549                                           Pandemic
1         822                                        Carcassonne
2          13                                              Catan
3       68448                                          7 Wonders
4       36218                                           Dominion
...       ...                                                ...
21834  285102                                    Dans les Cordes
21835  146746                                         Longstreet
21836   37718  The Games of War:  A Treasury of Rules for Bat...
21837   17684  Operation Star: The Soviet Winter Offensive, 1943
21838    1752                                               Haps

[21839 rows x 2 columns]

In [31]:
df.set_index('ID', inplace=True)

In [58]:
names = df.to_dict()
names

NameError: name 'df' is not defined

In [33]:
del df

In [63]:
import numpy as np
neighbors = indices[0][1:].tolist()

In [62]:
named = names['name']
named

{30549: 'Pandemic',
 822: 'Carcassonne',
 13: 'Catan',
 68448: '7 Wonders',
 36218: 'Dominion',
 9209: 'Ticket to Ride',
 178900: 'Codenames',
 167791: 'Terraforming Mars',
 173346: '7 Wonders Duel',
 31260: 'Agricola',
 3076: 'Puerto Rico',
 148228: 'Splendor',
 169786: 'Scythe',
 40692: 'Small World',
 14996: 'Ticket to Ride: Europe',
 230802: 'Azul',
 70323: 'King of Tokyo',
 129622: 'Love Letter',
 2651: 'Power Grid',
 266192: 'Wingspan',
 39856: 'Dixit',
 163412: 'Patchwork',
 84876: 'The Castles of Burgundy',
 478: 'Citadels',
 28143: 'Race for the Galaxy',
 110327: 'Lords of Waterdeep',
 174430: 'Gloomhaven',
 34635: 'Stone Age',
 161936: 'Pandemic Legacy: Season 1',
 65244: 'Forbidden Island',
 1927: 'Munchkin',
 12333: 'Twilight Struggle',
 120677: 'Terra Mystica',
 98778: 'Hanabi',
 150376: 'Dead of Winter: A Crossroads Game',
 54043: 'Jaipur',
 11: 'Bohnanza',
 10547: 'Betrayal at House on the Hill',
 50: 'Lost Cities',
 131357: 'Coup',
 147020: 'Star Realms',
 70919: 'Takenoko',
 133473: 'Sushi Go!',
 170216: 'Blood Rage',
 15987: 'Arkham Horror',
 41114: 'The Resistance',
 121921: 'Robinson Crusoe: Adventures on the Cursed Island',
 204583: 'Kingdomino',
 181304: 'Mysterium',
 183394: 'Viticulture Essential Edition',
 157354: 'Five Tribes',
 463: 'Magic: The Gathering',
 37111: 'Battlestar Galactica: The Board Game',
 126163: "Tzolk'in: The Mayan Calendar",
 205637: 'Arkham Horror: The Card Game',
 193738: 'Great Western Trail',
 162886: 'Spirit Island',
 201808: 'Clank!: A Deck-Building Adventure',
 2655: 'Hive',
 181: 'Risk',
 237182: 'Root',
 124361: 'Concordia',
 194655: 'Santorini',
 146021: 'Eldritch Horror',
 157969: 'Sheriff of Nottingham',
 40834: 'Dominion: Intrigue',
 31481: 'Galaxy Trucker',
 171: 'Chess',
 1406: 'Monopoly',
 199561: 'Sagrada',
 103343: 'A Game of Thrones: The Board Game (Second Edition)',
 6249: 'Alhambra',
 102794: 'Caverna: The Cave Farmers',
 244521: 'The Quacks of Quedlinburg',
 96848: 'Mage Knight Board Game',
 199792: 'Everdell',
 39463: 'Cosmic Encounter',
 128882: 'The Resistance: Avalon',
 205059: 'Mansions of Madness: Second Edition',
 143884: 'Machi Koro',
 320: 'Scrabble',
 132531: 'Roll for the Galaxy',
 35677: 'Le Havre',
 3955: 'BANG!',
 124742: 'Android: Netrunner',
 9220: 'Saboteur',
 18602: 'Caylus',
 136063: 'Forbidden Desert',
 148949: 'Istanbul',
 158899: 'Colt Express',
 72125: 'Eclipse',
 10630: "Memoir '44",
 42: 'Tigris & Euphrates',
 15062: 'Shadows over Camelot',
 192291: 'Sushi Go Party!',
 172: 'For Sale',
 182028: 'Through the Ages: A New Story of Civilization',
 187645: 'Star Wars: Rebellion',
 224517: 'Brass: Birmingham',
 146508: 'T.I.M.E Stories',
 284083: 'The Crew: The Quest for Planet Nine',
 172225: 'Exploding Kittens',
 122522: 'Smash Up',
 16992: 'Tsuro',
 50381: 'Cards Against Humanity',
 164928: 'Orléans',
 93: 'El Grande',
 2453: 'Blokus',
 153938: 'Camel Up',
 103885: 'Star Wars: X-Wing Miniatures Game',
 104162: 'Descent: Journeys in the Dark (Second Edition)',
 147949: 'One Night Ultimate Werewolf',
 2223: 'UNO',
 155426: 'Castles of Mad King Ludwig',
 100423: 'Elder Sign',
 432: '6 nimmt!',
 18: 'RoboRally',
 244992: 'The Mind',
 8217: 'San Juan',
 123260: 'Suburbia',
 154203: 'Imperial Settlers',
 123540: 'Tokaido',
 2653: 'Survive: Escape from Atlantis!',
 108745: 'Seasons',
 176494: 'Isle of Skye: From Chieftain to King',
 100901: 'Flash Point: Fire Rescue',
 12942: 'No Thanks!',
 77423: 'The Lord of the Rings: The Card Game',
 171623: 'The Voyages of Marco Polo',
 164153: 'Star Wars: Imperial Assault',
 233867: 'Welcome To...',
 104006: 'Village',
 143741: 'BANG! The Dice Game',
 28720: 'Brass: Lancashire',
 107529: 'Kingdom Builder',
 188834: 'Secret Hitler',
 129437: 'Legendary: A Marvel Deck Building Game',
 236457: 'Architects of the West Kingdom',
 209685: 'Century: Spice Road',
 73439: 'Troyes',
 122515: 'Keyflower',
 177736: 'A Feast for Odin',
 8203: "Hey, That's My Fish!",
 37046: 'Ghost Stories',
 116: 'Guillotine',
 12: 'Ra',
 161970: 'Alchemists',
 220308: 'Gaia Project',
 166384: 'Spyfall',
 218603: 'Photosynthesis',
 54998: 'Cyclades',
 5782: 'Coloretto',
 180263: 'The 7th Continent',
 62219: 'Dominant Species',
 27162: 'Kingsburg',
 5: 'Acquire',
 21790: 'Thurn and Taxis',
 198773: 'Codenames: Pictures',
 12493: 'Twilight Imperium: Third Edition',
 2511: 'Sherlock Holmes Consulting Detective: The Thames Murders & Other Cases',
 54: 'Tikal',
 1294: 'Clue',
 25613: 'Through the Ages: A Story of Civilization',
 170042: 'Raiders of the North Sea',
 15512: 'Diamant',
 118: 'Modern Art',
 74: 'Apples to Apples',
 92828: 'Dixit: Odyssey',
 43570: 'Friday',
 156129: 'Deception: Murder in Hong Kong',
 37904: 'Formula D',
 167355: 'Nemesis',
 124708: 'Mice and Mystics',
 205896: 'Rising Sun',
 171131: 'Captain Sonar',
 244522: "That's Pretty Clever!",
 113924: 'Zombicide',
 209778: 'Magic Maze',
 160477: 'Onitama',
 25669: 'Qwirkle',
 127023: 'Kemet',
 239188: 'Chronicles of Crime',
 28023: 'Jamaica',
 163967: 'Tiny Epic Galaxies',
 312484: 'Lost Ruins of Arnak',
 118048: 'Targi',
 194594: 'Dice Forge',
 62871: 'Zombie Dice',
 24480: 'The Pillars of the Earth',
 147151: 'Concept',
 263918: 'Cartographers',
 216132: 'Clans of Caledonia',
 224037: 'Codenames: Duet',
 92415: 'Skull',
 258: 'Fluxx',
 127398: 'Legends of Andor',
 760: 'Battle Line',
 21763: 'Mr. Jack',
 9674: 'Ingenious',
 233078: 'Twilight Imperium: Fourth Edition',
 291457: 'Gloomhaven: Jaws of the Lion',
 113294: 'Escape: The Curse of the Temple',
 34219: 'Biblios',
 144733: 'Russian Railroads',
 254640: 'Just One',
 63888: 'Innovation',
 169426: 'Roll Player',
 102680: 'Trajan',
 188: 'Go',
 115746: 'War of the Ring: Second Edition',
 217372: 'The Quest for El Dorado',
 175914: 'Food Chain Magnate',
 180974: 'Potion Explosion',
 3: 'Samurai',
 102652: 'Sentinels of the Multiverse',
 229853: 'Teotihuacan: City of Gods',
 38453: 'Space Alert',
 209010: 'Mechs vs. Minions',
 140934: 'Arboretum',
 438: 'Scotland Yard',
 9217: 'Saint Petersburg',
 316554: 'Dune: Imperium',
 160499: 'King of New York',
 77130: "Sid Meier's Civilization: The Board Game",
 43443: 'Castle Panic',
 555: 'The Princes of Florence',
 823: 'The Lord of the Rings',
 182874: 'Grand Austria Hotel',
 131835: 'Boss Monster: The Dungeon Building Card Game',
 2471: 'Zombies!!!',
 43111: 'Chaos in the Old World',
 172287: 'Champions of Midgard',
 155821: 'Inis',
 155703: 'Evolution',
 225694: 'Decrypto',
 41: "Can't Stop",
 48726: 'Alien Frontiers',
 1917: 'Stratego',
 811: 'Rummikub',
 59959: 'Letters from Whitechapel',
 63268: 'Spot it!',
 156009: 'Port Royal',
 286096: 'Tapestry',
 27588: 'Zooloretto',
 12692: 'Gloom',
 46213: 'Telestrations',
 199042: 'Harry Potter: Hogwarts Battle',
 285774: 'Marvel Champions: The Card Game',
 262712: 'Res Arcana',
 219513: 'Bärenpark',
 172818: 'Above and Below',
 198994: 'Hero Realms',
 20100: 'Wits & Wagers',
 140620: 'Lewis & Clark: The Expedition',
 199478: 'Flamme Rouge',
 27627: 'Talisman: Revised 4th Edition',
 215: 'Tichu',
 191189: "Aeon's End",
 21241: 'Neuroshima Hex! 3.0',
 29368: 'Last Night on Earth: The Zombie Game',
 176189: 'Zombicide: Black Plague',
 161417: 'Red7',
 221107: 'Pandemic Legacy: Season 2',
 97207: 'Dungeon Petz',
 521: 'Crokinole',
 155362: "Ca$h 'n Guns (Second Edition)",
 91536: 'Quarriors!',
 185343: 'Anachrony',
 278: 'Catan Card Game',
 19857: 'Glory to Rome',
 45: 'Perudo',
 45315: 'Dungeon Lords',
 265736: 'Tiny Towns',
 25292: 'Merchants & Marauders',
 20551: 'Shogun',
 221194: 'Dinosaur Island',
 503: 'Through the Desert',
 191862: 'Imhotep',
 83330: 'Mansions of Madness',
 171668: 'The Grizzled',
 256382: 'Disney Villainous',
 158600: 'Hanamikoji',
 125618: 'Libertalia',
 247763: 'Underwater Cities',
 119890: 'Agricola: All Creatures Big and Small',
 197376: 'Charterstone',
 2243: 'Yahtzee',
 266524: 'PARKS',
 43015: 'Hansa Teutonica',
 2452: 'Jenga',
 71721: 'Space Hulk: Death Angel – The Card Game',
 25554: 'Notre Dame',
 181279: 'Fury of Dracula (Third/Fourth Edition)',
 150312: 'Welcome to the Dungeon',
 483: 'Diplomacy',
 31627: 'Ticket to Ride: Nordic Countries',
 2397: 'Backgammon',
 69789: 'Ascension: Deckbuilding Game',
 66188: 'Fresco',
 133038: 'Pathfinder Adventure Card Game: Rise of the Runelords – Base Set',
 169654: 'Deep Sea Adventure',
 34119: 'Tales of the Arabian Nights',
 146652: 'Legendary Encounters: An Alien Deck Building Game',
 8098: 'Jungle Speed',
 4390: 'Carcassonne: Hunters and Gatherers',
 176396: 'Quadropolis',
 200680: 'Agricola (Revised Edition)',
 37380: 'Roll Through the Ages: The Bronze Age',
 274960: 'Point Salad',
 172386: 'Mombasa',
 155987: 'Abyss',
 699: 'HeroQuest',
 126042: 'Nations',
 17226: 'Descent: Journeys in the Dark',
 1198: 'SET',
 17133: 'Railways of the World',
 1219: 'Labyrinth',
 2921: 'The Game of Life',
 269385: 'The Lord of the Rings: Journeys in Middle-Earth',
 128621: 'Viticulture',
 31594: 'In the Year of the Dragon',
 242302: 'Space Base',
 266810: 'Paladins of the West Kingdom',
 281259: 'The Isle of Cats',
 42215: 'Tobago',
 1111: 'Taboo',
 125153: 'The Gallerist',
 9216: 'Goa',
 138161: 'Firefly: The Game',
 221965: 'The Fox in the Forest',
 206718: 'Ethnos',
 233371: 'Clank! In! Space!: A Deck-Building Adventure',
 203993: 'Lorenzo il Magnifico',
 276025: 'Maracaibo',
 136888: 'Bruges',
 131260: 'Qwixx',
 90137: 'Blood Bowl: Team Manager – The Card Game',
 93260: 'Summoner Wars: Master Set',
 98: 'Axis & Allies',
 183840: 'Oh My Goods!',
 220877: 'Rajas of the Ganges',
 25821: "The Werewolves of Miller's Hollow",
 256226: 'Azul: Stained Glass of Sintra',
 6472: 'A Game of Thrones',
 53953: 'Thunderstone',
 39683: 'At the Gates of Loyang',
 160851: 'Lanterns: The Harvest Festival',
 220: 'High Society',
 97786: 'Small World Underground',
 9609: 'War of the Ring',
 70149: 'Ora et Labora',
 257501: 'KeyForge: Call of the Archons',
 150: 'PitchCar',
 168435: 'Between Two Cities',
 287954: 'Azul: Summer Pavilion',
 22545: 'Age of Empires III: The Age of Discovery',
 19237: "Ca$h 'n Gun$",
 133848: 'Euphoria: Build a Better Dystopia',
 271324: "It's a Wonderful World",
 11971: 'Cockroach Poker',
 188920: 'This War of Mine: The Board Game',
 68425: 'Eminent Domain',
 194607: 'Mystic Vale',
 117959: 'Las Vegas',
 196340: 'Yokohama',
 150658: 'Pandemic: The Cure',
 27833: 'Steam',
 1115: 'Poker',
 203420: 'Exit: The Game – The Abandoned Cabin',
 215311: 'Downforce',
 245638: 'Coimbra',
 143693: 'Glass Road',
 282524: 'Horrified',
 139030: 'Mascarade',
 91312: 'Discworld: Ankh-Morpork',
 176920: 'Mission: Red Planet (Second Edition)',
 73761: 'K2',
 155068: 'Arcadia Quest',
 141572: 'Paperback',
 15818: 'Pickomino',
 40398: 'Monopoly Deal Card Game',
 146886: 'La Granja',
 251247: 'Barrage',
 183251: 'Karuba',
 4098: 'Age of Steam',
 27225: 'Bananagrams',
 97842: 'Last Will',
 127060: 'Bora Bora',
 30869: 'Thebes',
 173090: 'The Game',
 63628: 'The Manhattan Project',
 205398: 'Citadels',
 246784: 'Cryptid',
 1465: 'Wizard',
 33160: 'Endeavor',
 175117: 'Celestia',
 172081: 'Burgle Bros.',
 177524: 'ICECOOL',
 171499: 'Cacao',
 25417: 'BattleLore',
 91514: 'Rhino Hero',
 2425: 'Battleship',
 47: 'Chinatown',
 179275: 'One Deck Dungeon',
 20963: 'Fury of Dracula (Second Edition)',
 2381: 'Scattergories',
 112: 'Condottiere',
 159675: 'Fields of Arle',
 88: 'Torres',
 232043: 'Queendomino',
 184921: 'Bunny Kingdom',
 163968: 'Elysium',
 891: 'Cranium',
 198928: 'Pandemic: Iberia',
 66362: 'Glen More',
 194879: 'Not Alone',
 245654: 'Railroad Ink: Deep Blue Edition',
 21348: 'Ticket to Ride: Märklin',
 394: 'Kahuna',
 156336: 'Onirim (Second Edition)',
 2398: 'Cribbage',
 27708: '1960: The Making of the President',
 172308: 'Broom Service',
 5404: 'Amun-Re',
 327: "Loopin' Louie",
 59946: 'Dungeons & Dragons: Castle Ravenloft Board Game',
 246192: 'Gizmos',
 372: 'Schotten Totten',
 269207: 'The Taverns of Tiefenthal',
 192153: 'Pandemic: Reign of Cthulhu',
 13823: 'Fairy Tale',
 27746: 'Colosseum',
 15363: 'Nexus Ops',
 140: 'Pit',
 177639: 'Raptor',
 283155: 'Calico',
 193037: 'Dead of Winter: The Long Night',
 172242: 'Exploding Kittens: NSFW Deck',
 232832: 'Century: Golem Edition',
 66589: 'Navegador',
 1258: 'Phase 10',
 24181: 'Imperial',
 1234: 'Once Upon a Time: The Storytelling Card Game',
 195421: 'Near and Far',
 10: 'Elfenland',
 223321: 'Detective: A Modern Crime Board Game',
 51: 'Ricochet Robots',
 16986: 'Ubongo',
 163602: 'XCOM: The Board Game',
 2375: 'Sequence',
 82222: 'Xia: Legends of a Drift System',
 169124: "Flick 'em Up!",
 24068: 'Shadow Hunters',
 13308: 'Niagara',
 14105: 'Commands & Colors: Ancients',
 27173: 'Vikings',
 24508: 'Taluva',
 55690: 'Kingdom Death: Monster',
 12002: 'Jambo',
 264220: 'Tainted Grail: The Fall of Avalon',
 2987: "Pirate's Cove",
 232405: 'Western Legends',
 30380: 'Cuba',
 175155: 'Forbidden Stars',
 72287: 'Mr. Jack Pocket',
 144344: 'Rococo',
 59294: 'Runewars',
 11170: 'Heroscape Master Set: Rise of the Valkyrie',
 121408: 'Trains',
 21882: 'Blue Moon City',
 161533: 'Lisboa',
 131366: 'Eight-Minute Empire',
 184267: 'On Mars',
 22345: 'Yspahan',
 21523: 'Runebound: Second Edition',
 2842: 'TransAmerica',
 105134: 'Risk Legacy',
 192135: 'Too Many Bones',
 138788: 'Dungeon Roll',
 36946: 'Red November',
 7854: 'YINSH',
 162082: 'Deus',
 915: 'Mystery of the Abbey',
 7805: 'Fearsome Floors',
 122298: 'Morels',
 137297: 'Rise of Augustus',
 7717: 'Carcassonne: The Castle',
 223040: 'Fantasy Realms',
 163068: 'Trickerion: Legends of Illusion',
 13004: 'The Downfall of Pompeii',
 264055: 'Draftosaurus',
 234487: 'Altiplano',
 244228: 'Reef',
 31730: 'Chicago Express',
 200147: 'Kanagawa',
 105551: 'Archipelago',
 2952: 'Trivial Pursuit: Genus Edition',
 128671: 'Spartacus: A Game of Blood and Treachery',
 590: 'Mille Bornes',
 826: 'Cartagena',
 79828: 'A Few Acres of Snow',
 171273: 'FUSE',
 207830: '5-Minute Dungeon',
 85256: 'Timeline: Inventions',
 101721: 'Mage Wars Arena',
 2083: 'Checkers',
 17329: 'Animal Upon Animal',
 204027: 'Cottage Garden',
 83195: 'Ghost Blitz',
 24310: 'The Red Dragon Inn',
 2719: 'Connect Four',
 46: 'Medici',
 2389: 'Othello',
 1293: 'Boggle',
 271896: 'Star Wars: Outer Rim',
 148951: 'Tiny Epic Kingdoms',
 97903: 'Terror in Meeple City',
 475: 'Taj Mahal',
 2281: 'Pictionary',
 233398: 'Endeavor: Age of Sail',
 71: 'Civilization',
 929: 'The Great Dalmuti',
 22827: 'StarCraft: The Board Game',
 227789: 'Heaven & Ale',
 55670: 'Macao',
 105: 'Colossal Arena',
 250458: 'Gùgōng',
 40793: 'Dice Town',
 90419: 'Airlines Europe',
 180593: 'The Bloody Inn',
 40628: 'Finca',
 155695: 'Age of War',
 176229: 'Tides of Time',
 274364: 'Watergate',
 228341: 'Pulsar 2849',
 96913: 'Lancaster',
 39938: 'Carson City',
 20437: 'Lords of Vegas',
 143519: 'Quantum',
 624: 'Quoridor',
 1829: 'Risk 2210 A.D.',
 110277: 'Among the Stars',
 165722: 'KLASK',
 54625: 'Space Hulk (Third Edition)',
 159508: 'AquaSphere',
 36932: 'Claustrophobia',
 256960: 'Pax Pamir: Second Edition',
 2093: 'Mahjong',
 182631: 'Star Realms: Colony Wars',
 526: 'Abalone',
 1269: 'Skip-Bo',
 257: 'Kill Doctor Lucky',
 182134: 'Evolution: Climate',
 134726: 'Smash Up: Awesome Level 9000',
 3201: 'Lord of the Rings: The Confrontation',
 125678: 'DC Comics Deck-Building Game',
 201921: 'Tiny Epic Quest',
 318977: 'MicroMacro: Crime City',
 2392: 'Mastermind',
 146278: 'Tash-Kalar: Arena of Legends',
 232219: 'Dragon Castle',
 8051: 'Attika',
 140933: 'Blueprints',
 22141: 'Cleopatra and the Society of Architects',
 65781: 'London',
 262543: 'Wavelength',
 56692: 'Parade',
 195539: "The Godfather: Corleone's Empire",
 66056: 'Rivals for Catan',
 681: 'Quarto',
 166669: 'San Juan (Second Edition)',
 251658: 'Sprawlopolis',
 58281: 'Summoner Wars',
 268864: 'Undaunted: Normandy',
 29387: 'Zombie Fluxx',
 257499: 'Arkham Horror (Third Edition)',
 217449: 'NMBR 9',
 2448: 'Kalah',
 2394: 'Dominoes',
 192457: 'Cry Havoc',
 30539: 'Get Bit!',
 109276: "Kanban: Driver's Edition",
 269210: 'Twice as Clever!',
 242574: 'Century: Eastern Wonders',
 170416: 'Vast: The Crystal Caverns',
 2407: 'Sorry!',
 770: 'Loot',
 38054: 'Snow Tails',
 15364: 'Vegas Showdown',
 191977: 'The Castles of Burgundy: The Card Game',
 222509: 'Lords of Hellas',
 203417: 'Exit: The Game – The Secret Lab',
 127024: 'Room 25',
 175324: 'Fog of Love',
 194880: 'Dream Home',
 162007: 'Steampunk Rally',
 232918: 'Fallout',
 66356: 'Dungeons & Dragons: Wrath of Ashardalon Board Game',
 39953: 'A Game of Thrones: The Card Game',
 50750: 'Belfort',
 102548: 'Dungeon Fighter',
 293014: 'Nidavellir',
 171233: 'The Big Book of Madness',
 193042: 'Junk Art',
 71836: 'Onirim',
 143986: 'CV',
 161614: 'Stockpile',
 124172: 'Tsuro of the Seas',
 54138: 'Imperial 2030',
 1345: 'Genoa',
 137269: 'Spyrium',
 189932: 'Tyrants of the Underdark',
 202408: 'Adrenaline',
 34585: 'Keltis',
 155624: 'Specter Ops',
 146439: 'BattleLore: Second Edition',
 10093: 'Axis & Allies',
 128271: 'Ginkgopolis',
 253344: 'Cthulhu: Death May Die',
 44163: 'Power Grid: Factory Manager',
 136991: 'Loony Quest',
 213893: 'Yamataï',
 91872: 'Dungeons & Dragons: The Legend of Drizzt Board Game',
 12995: 'Dungeon Twister',
 5716: 'Balloon Cup',
 18833: 'Lord of the Rings: The Confrontation',
 112686: 'Epic Spell Wars of the Battle Wizards: Duel at Mt. Skullzfyre',
 49: 'Mamma Mia!',
 33604: 'Say Anything',
 203416: "Exit: The Game – The Pharaoh's Tomb",
 559: 'Metro',
 42452: 'Rattus',
 47185: 'Warhammer: Invasion',
 229220: 'Santa Maria',
 260605: 'Camel Up (Second Edition)',
 174660: 'New York 1901',
 137408: 'Amerigo',
 72321: 'The Networks',
 245934: 'Carpe Diem',
 121410: 'Steam Park',
 15817: 'Manila',
 192458: '51st State: Master Set',
 163: 'Balderdash',
 209418: 'Dominion (Second Edition)',
 135779: 'A Fake Artist Goes to New York',
 3699: 'Killer Bunnies and the Quest for the Magic Carrot',
 220520: 'Caverna: Cave vs Cave',
 121: 'Dune',
 216459: 'The Lost Expedition',
 9446: 'Blue Moon',
 156566: 'Lords of Xidit',
 2593: 'Pass the Pigs',
 148575: 'Marvel Dice Masters: Avengers vs. X-Men',
 230080: 'Majesty: For the Realm',
 21050: 'Combat Commander: Europe',
 201825: 'Ex Libris',
 27710: 'Catan Dice Game',
 249259: 'War Chest',
 200077: 'Mint Works',
 17223: 'World of Warcraft: The Boardgame',
 39351: 'Automobile',
 242: 'Junta',
 103886: 'Star Wars: The Card Game',
 296151: 'Viscounts of the West Kingdom',
 167400: 'Ashes Reborn: Rise of the Phoenixborn',
 233312: 'Stuffed Fables',
 246900: 'Eclipse: Second Dawn for the Galaxy',
 203427: 'Fabled Fruit',
 815: 'Chrononauts',
 13642: 'Louis XIV',
 712: 'Blood Bowl (Third Edition)',
 1: 'Die Macher',
 181530: 'Runebound (Third Edition)',
 40765: 'Clash of Cultures',
 253284: 'Ticket to Ride: New York',
 270673: 'Silver & Gold',
 234190: 'Unstable Unicorns',
 236191: 'London (Second Edition)',
 16395: 'Blokus Duo',
 2955: 'Mexica',
 1353: "Time's Up!",
 65532: 'Defenders of the Realm',
 150145: 'Skull King',
 41916: 'The Magic Labyrinth',
 157526: 'Viceroy',
 181810: 'Kodama: The Tree Spirits',
 224783: 'Vindication',
 714: 'Talisman',
 58421: 'Egizia',
 266083: 'L.L.A.M.A.',
 168584: 'Love Letter: Batman',
 126792: 'Myrmes',
 163166: 'One Night Ultimate Werewolf: Daybreak',
 199: 'Manhattan',
 1382: "Winner's Circle",
 157809: 'Nations: The Dice Game',
 904: 'Dream Factory',
 102104: 'Star Fluxx',
 176734: 'The Manhattan Project: Energy Empire',
 154246: 'La Isla',
 241724: 'Villagers',
 206941: 'First Class: All Aboard the Orient Express!',
 244711: 'Newton',
 554: 'La Città',
 270844: 'Imperial Settlers: Empires of the North',
 157403: 'Black Fleet',
 1897: 'The Starfarers of Catan',
 4143: 'Guess Who?',
 181521: 'Warhammer Quest: The Adventure Card Game',
 25071: 'Munchkin Cthulhu',
 10640: 'Doom: The Boardgame',
 152162: 'Diamonds: Second Edition',
 233247: 'Civilization: A New Dawn',
 265188: 'Glen More II: Chronicles',
 120: 'Hoity Toity',
 113997: 'Tajemnicze Domostwo',
 12962: 'Reef Encounter',
 8989: 'Hansa',

In [66]:
for n in neighbors:
    try:
        print(named[n])

SyntaxError: unexpected EOF while parsing (3497264960.py, line 3)

In [74]:
named[16088]

'Calaboose'

In [70]:
neighbors

[2677, 4690, 406, 470]